// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: proto/sardine.proto

package sardine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegSectionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag   string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"` // 默认支持 int32(0) - int32(math.MaxInt32) 范围
	Async bool   `protobuf:"varint,2,opt,name=async,proto3" json:"async,omitempty"`
}

func (x *RegSectionReq) Reset() {
	*x = RegSectionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegSectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegSectionReq) ProtoMessage() {}

func (x *RegSectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegSectionReq.ProtoReflect.Descriptor instead.
func (*RegSectionReq) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{0}
}

func (x *RegSectionReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *RegSectionReq) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

type RegSectionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegSectionResp) Reset() {
	*x = RegSectionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegSectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegSectionResp) ProtoMessage() {}

func (x *RegSectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegSectionResp.ProtoReflect.Descriptor instead.
func (*RegSectionResp) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{1}
}

type UnRegSectionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag   string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"` // 默认支持 int32(0) - int32(math.MaxInt32) 范围
	Async bool   `protobuf:"varint,2,opt,name=async,proto3" json:"async,omitempty"`
}

func (x *UnRegSectionReq) Reset() {
	*x = UnRegSectionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegSectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegSectionReq) ProtoMessage() {}

func (x *UnRegSectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegSectionReq.ProtoReflect.Descriptor instead.
func (*UnRegSectionReq) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{2}
}

func (x *UnRegSectionReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *UnRegSectionReq) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

type UnRegSectionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnRegSectionResp) Reset() {
	*x = UnRegSectionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnRegSectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnRegSectionResp) ProtoMessage() {}

func (x *UnRegSectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnRegSectionResp.ProtoReflect.Descriptor instead.
func (*UnRegSectionResp) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{3}
}

type ReBalanceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReBalanceReq) Reset() {
	*x = ReBalanceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReBalanceReq) ProtoMessage() {}

func (x *ReBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReBalanceReq.ProtoReflect.Descriptor instead.
func (*ReBalanceReq) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{4}
}

type ReBalanceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReBalanceResp) Reset() {
	*x = ReBalanceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReBalanceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReBalanceResp) ProtoMessage() {}

func (x *ReBalanceResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReBalanceResp.ProtoReflect.Descriptor instead.
func (*ReBalanceResp) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{5}
}

type GenUserSeqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *GenUserSeqReq) Reset() {
	*x = GenUserSeqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenUserSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenUserSeqReq) ProtoMessage() {}

func (x *GenUserSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenUserSeqReq.ProtoReflect.Descriptor instead.
func (*GenUserSeqReq) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{6}
}

func (x *GenUserSeqReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GenUserSeqReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type GenUserSeqResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GenUserSeqResp) Reset() {
	*x = GenUserSeqResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenUserSeqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenUserSeqResp) ProtoMessage() {}

func (x *GenUserSeqResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenUserSeqResp.ProtoReflect.Descriptor instead.
func (*GenUserSeqResp) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{7}
}

func (x *GenUserSeqResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserSeqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag string `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *GetUserSeqReq) Reset() {
	*x = GetUserSeqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSeqReq) ProtoMessage() {}

func (x *GetUserSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSeqReq.ProtoReflect.Descriptor instead.
func (*GetUserSeqReq) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserSeqReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserSeqReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type GetUserSeqResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetUserSeqResp) Reset() {
	*x = GetUserSeqResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserSeqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSeqResp) ProtoMessage() {}

func (x *GetUserSeqResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSeqResp.ProtoReflect.Descriptor instead.
func (*GetUserSeqResp) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserSeqResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GenUserMultiSeqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TagList []string `protobuf:"bytes,2,rep,name=tagList,proto3" json:"tagList,omitempty"`
	Async   bool     `protobuf:"varint,3,opt,name=async,proto3" json:"async,omitempty"`
}

func (x *GenUserMultiSeqReq) Reset() {
	*x = GenUserMultiSeqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenUserMultiSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenUserMultiSeqReq) ProtoMessage() {}

func (x *GenUserMultiSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenUserMultiSeqReq.ProtoReflect.Descriptor instead.
func (*GenUserMultiSeqReq) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{10}
}

func (x *GenUserMultiSeqReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GenUserMultiSeqReq) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

func (x *GenUserMultiSeqReq) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

type GenUserMultiSeqResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqList map[string]int64 `protobuf:"bytes,1,rep,name=SeqList,proto3" json:"SeqList,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *GenUserMultiSeqResp) Reset() {
	*x = GenUserMultiSeqResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenUserMultiSeqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenUserMultiSeqResp) ProtoMessage() {}

func (x *GenUserMultiSeqResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenUserMultiSeqResp.ProtoReflect.Descriptor instead.
func (*GenUserMultiSeqResp) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{11}
}

func (x *GenUserMultiSeqResp) GetSeqList() map[string]int64 {
	if x != nil {
		return x.SeqList
	}
	return nil
}

type GetUserMultiSeqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TagList []string `protobuf:"bytes,2,rep,name=tagList,proto3" json:"tagList,omitempty"`
}

func (x *GetUserMultiSeqReq) Reset() {
	*x = GetUserMultiSeqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserMultiSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMultiSeqReq) ProtoMessage() {}

func (x *GetUserMultiSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMultiSeqReq.ProtoReflect.Descriptor instead.
func (*GetUserMultiSeqReq) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserMultiSeqReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserMultiSeqReq) GetTagList() []string {
	if x != nil {
		return x.TagList
	}
	return nil
}

type GetUserMultiSeqResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqList map[string]int64 `protobuf:"bytes,1,rep,name=SeqList,proto3" json:"SeqList,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *GetUserMultiSeqResp) Reset() {
	*x = GetUserMultiSeqResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserMultiSeqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserMultiSeqResp) ProtoMessage() {}

func (x *GetUserMultiSeqResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserMultiSeqResp.ProtoReflect.Descriptor instead.
func (*GetUserMultiSeqResp) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserMultiSeqResp) GetSeqList() map[string]int64 {
	if x != nil {
		return x.SeqList
	}
	return nil
}

type BatchGenUserSeqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdList []uint32 `protobuf:"varint,1,rep,packed,name=idList,proto3" json:"idList,omitempty"`
	Tag    string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Async  bool     `protobuf:"varint,3,opt,name=async,proto3" json:"async,omitempty"`
}

func (x *BatchGenUserSeqReq) Reset() {
	*x = BatchGenUserSeqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGenUserSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGenUserSeqReq) ProtoMessage() {}

func (x *BatchGenUserSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGenUserSeqReq.ProtoReflect.Descriptor instead.
func (*BatchGenUserSeqReq) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{14}
}

func (x *BatchGenUserSeqReq) GetIdList() []uint32 {
	if x != nil {
		return x.IdList
	}
	return nil
}

func (x *BatchGenUserSeqReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *BatchGenUserSeqReq) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

type BatchGenUserSeqResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqList map[uint32]int64 `protobuf:"bytes,1,rep,name=SeqList,proto3" json:"SeqList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *BatchGenUserSeqResp) Reset() {
	*x = BatchGenUserSeqResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGenUserSeqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGenUserSeqResp) ProtoMessage() {}

func (x *BatchGenUserSeqResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGenUserSeqResp.ProtoReflect.Descriptor instead.
func (*BatchGenUserSeqResp) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{15}
}

func (x *BatchGenUserSeqResp) GetSeqList() map[uint32]int64 {
	if x != nil {
		return x.SeqList
	}
	return nil
}

type BatchGetUserSeqReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdList []uint32 `protobuf:"varint,1,rep,packed,name=idList,proto3" json:"idList,omitempty"`
	Tag    string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *BatchGetUserSeqReq) Reset() {
	*x = BatchGetUserSeqReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetUserSeqReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserSeqReq) ProtoMessage() {}

func (x *BatchGetUserSeqReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserSeqReq.ProtoReflect.Descriptor instead.
func (*BatchGetUserSeqReq) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{16}
}

func (x *BatchGetUserSeqReq) GetIdList() []uint32 {
	if x != nil {
		return x.IdList
	}
	return nil
}

func (x *BatchGetUserSeqReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type BatchGetUserSeqResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqList map[uint32]int64 `protobuf:"bytes,1,rep,name=SeqList,proto3" json:"SeqList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *BatchGetUserSeqResp) Reset() {
	*x = BatchGetUserSeqResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sardine_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetUserSeqResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserSeqResp) ProtoMessage() {}

func (x *BatchGetUserSeqResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sardine_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserSeqResp.ProtoReflect.Descriptor instead.
func (*BatchGetUserSeqResp) Descriptor() ([]byte, []int) {
	return file_proto_sardine_proto_rawDescGZIP(), []int{17}
}

func (x *BatchGetUserSeqResp) GetSeqList() map[uint32]int64 {
	if x != nil {
		return x.SeqList
	}
	return nil
}

var File_proto_sardine_proto protoreflect.FileDescriptor

var file_proto_sardine_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x22, 0x37,
	0x0a, 0x0d, 0x52, 0x65, 0x67, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x22, 0x10, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x53, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x39, 0x0a, 0x0f, 0x55, 0x6e, 0x52,
	0x65, 0x67, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61,
	0x73, 0x79, 0x6e, 0x63, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x53, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x42, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x31, 0x0a, 0x0d, 0x47, 0x65, 0x6e,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x20, 0x0a, 0x0e,
	0x47, 0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x31,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61,
	0x67, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x54, 0x0a, 0x12, 0x47, 0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x67,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x61, 0x73, 0x79, 0x6e, 0x63, 0x22, 0x96, 0x01, 0x0a, 0x13, 0x47, 0x65,
	0x6e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x43, 0x0a, 0x07, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x29, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x6e,
	0x55, 0x73, 0x65, 0x72, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70,
	0x2e, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x53,
	0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x3a, 0x0a, 0x0c, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x3e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x96, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x12, 0x43, 0x0a, 0x07, 0x53, 0x65,
	0x71, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x53, 0x61,
	0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x75, 0x6c,
	0x74, 0x69, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x1a,
	0x3a, 0x0a, 0x0c, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x54, 0x0a, 0x12, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x06, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x73, 0x79, 0x6e, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x73, 0x79, 0x6e,
	0x63, 0x22, 0x96, 0x01, 0x0a, 0x13, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x6e, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x12, 0x43, 0x0a, 0x07, 0x53, 0x65, 0x71,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x53, 0x61, 0x72,
	0x64, 0x69, 0x6e, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x6e, 0x55, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x3a,
	0x0a, 0x0c, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3e, 0x0a, 0x12, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d,
	0x52, 0x06, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x96, 0x01, 0x0a, 0x13, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x43, 0x0a, 0x07, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73,
	0x70, 0x2e, 0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x53, 0x65, 0x71, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x3a, 0x0a, 0x0c, 0x53, 0x65, 0x71, 0x4c, 0x69,
	0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x32, 0xce, 0x01, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x3f,
	0x0a, 0x0a, 0x52, 0x65, 0x67, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x2e, 0x53,
	0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x52,
	0x65, 0x67, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x45, 0x0a, 0x0c, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x53,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x53, 0x61, 0x72, 0x64,
	0x69, 0x6e, 0x65, 0x2e, 0x55, 0x6e, 0x52, 0x65, 0x67, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x09, 0x52, 0x65, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x65,
	0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x53, 0x61, 0x72,
	0x64, 0x69, 0x6e, 0x65, 0x2e, 0x52, 0x65, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x32, 0x89, 0x01, 0x0a, 0x05, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x12, 0x3f,
	0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x12, 0x16, 0x2e, 0x53,
	0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x71, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x47,
	0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x3f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x12, 0x16, 0x2e,
	0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x71, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x32, 0xc9, 0x03, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x3f, 0x0a, 0x0a, 0x47, 0x65,
	0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x12, 0x16, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69,
	0x6e, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0a, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x12, 0x16, 0x2e, 0x53, 0x61, 0x72, 0x64,
	0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65,
	0x71, 0x1a, 0x17, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0f,
	0x47, 0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x65, 0x71, 0x12,
	0x1b, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x53,
	0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x65, 0x71, 0x12,
	0x1b, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x53,
	0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0f,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x12,
	0x1b, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47,
	0x65, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x53,
	0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x6e, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0f,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x12,
	0x1b, 0x2e, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x53,
	0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x65, 0x73, 0x74, 0x6c,
	0x61, 0x73, 0x63, 0x6f, 0x72, 0x70, 0x69, 0x6f, 0x6e, 0x2f, 0x53, 0x61, 0x72, 0x64, 0x69, 0x6e,
	0x65, 0x3b, 0x73, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_sardine_proto_rawDescOnce sync.Once
	file_proto_sardine_proto_rawDescData = file_proto_sardine_proto_rawDesc
)

func file_proto_sardine_proto_rawDescGZIP() []byte {
	file_proto_sardine_proto_rawDescOnce.Do(func() {
		file_proto_sardine_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_sardine_proto_rawDescData)
	})
	return file_proto_sardine_proto_rawDescData
}

var file_proto_sardine_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_sardine_proto_goTypes = []interface{}{
	(*RegSectionReq)(nil),       // 0: Sardine.RegSectionReq
	(*RegSectionResp)(nil),      // 1: Sardine.RegSectionResp
	(*UnRegSectionReq)(nil),     // 2: Sardine.UnRegSectionReq
	(*UnRegSectionResp)(nil),    // 3: Sardine.UnRegSectionResp
	(*ReBalanceReq)(nil),        // 4: Sardine.ReBalanceReq
	(*ReBalanceResp)(nil),       // 5: Sardine.ReBalanceResp
	(*GenUserSeqReq)(nil),       // 6: Sardine.GenUserSeqReq
	(*GenUserSeqResp)(nil),      // 7: Sardine.GenUserSeqResp
	(*GetUserSeqReq)(nil),       // 8: Sardine.GetUserSeqReq
	(*GetUserSeqResp)(nil),      // 9: Sardine.GetUserSeqResp
	(*GenUserMultiSeqReq)(nil),  // 10: Sardine.GenUserMultiSeqReq
	(*GenUserMultiSeqResp)(nil), // 11: Sardine.GenUserMultiSeqResp
	(*GetUserMultiSeqReq)(nil),  // 12: Sardine.GetUserMultiSeqReq
	(*GetUserMultiSeqResp)(nil), // 13: Sardine.GetUserMultiSeqResp
	(*BatchGenUserSeqReq)(nil),  // 14: Sardine.BatchGenUserSeqReq
	(*BatchGenUserSeqResp)(nil), // 15: Sardine.BatchGenUserSeqResp
	(*BatchGetUserSeqReq)(nil),  // 16: Sardine.BatchGetUserSeqReq
	(*BatchGetUserSeqResp)(nil), // 17: Sardine.BatchGetUserSeqResp
	nil,                         // 18: Sardine.GenUserMultiSeqResp.SeqListEntry
	nil,                         // 19: Sardine.GetUserMultiSeqResp.SeqListEntry
	nil,                         // 20: Sardine.BatchGenUserSeqResp.SeqListEntry
	nil,                         // 21: Sardine.BatchGetUserSeqResp.SeqListEntry
}
var file_proto_sardine_proto_depIdxs = []int32{
	18, // 0: Sardine.GenUserMultiSeqResp.SeqList:type_name -> Sardine.GenUserMultiSeqResp.SeqListEntry
	19, // 1: Sardine.GetUserMultiSeqResp.SeqList:type_name -> Sardine.GetUserMultiSeqResp.SeqListEntry
	20, // 2: Sardine.BatchGenUserSeqResp.SeqList:type_name -> Sardine.BatchGenUserSeqResp.SeqListEntry
	21, // 3: Sardine.BatchGetUserSeqResp.SeqList:type_name -> Sardine.BatchGetUserSeqResp.SeqListEntry
	0,  // 4: Sardine.assign.RegSection:input_type -> Sardine.RegSectionReq
	2,  // 5: Sardine.assign.UnRegSection:input_type -> Sardine.UnRegSectionReq
	4,  // 6: Sardine.assign.ReBalance:input_type -> Sardine.ReBalanceReq
	6,  // 7: Sardine.alloc.GenUserSeq:input_type -> Sardine.GenUserSeqReq
	8,  // 8: Sardine.alloc.GetUserSeq:input_type -> Sardine.GetUserSeqReq
	6,  // 9: Sardine.proxy.GenUserSeq:input_type -> Sardine.GenUserSeqReq
	8,  // 10: Sardine.proxy.GetUserSeq:input_type -> Sardine.GetUserSeqReq
	10, // 11: Sardine.proxy.GenUserMultiSeq:input_type -> Sardine.GenUserMultiSeqReq
	12, // 12: Sardine.proxy.GetUserMultiSeq:input_type -> Sardine.GetUserMultiSeqReq
	14, // 13: Sardine.proxy.BatchGenUserSeq:input_type -> Sardine.BatchGenUserSeqReq
	16, // 14: Sardine.proxy.BatchGetUserSeq:input_type -> Sardine.BatchGetUserSeqReq
	1,  // 15: Sardine.assign.RegSection:output_type -> Sardine.RegSectionResp
	3,  // 16: Sardine.assign.UnRegSection:output_type -> Sardine.UnRegSectionResp
	5,  // 17: Sardine.assign.ReBalance:output_type -> Sardine.ReBalanceResp
	7,  // 18: Sardine.alloc.GenUserSeq:output_type -> Sardine.GenUserSeqResp
	9,  // 19: Sardine.alloc.GetUserSeq:output_type -> Sardine.GetUserSeqResp
	7,  // 20: Sardine.proxy.GenUserSeq:output_type -> Sardine.GenUserSeqResp
	9,  // 21: Sardine.proxy.GetUserSeq:output_type -> Sardine.GetUserSeqResp
	11, // 22: Sardine.proxy.GenUserMultiSeq:output_type -> Sardine.GenUserMultiSeqResp
	13, // 23: Sardine.proxy.GetUserMultiSeq:output_type -> Sardine.GetUserMultiSeqResp
	15, // 24: Sardine.proxy.BatchGenUserSeq:output_type -> Sardine.BatchGenUserSeqResp
	17, // 25: Sardine.proxy.BatchGetUserSeq:output_type -> Sardine.BatchGetUserSeqResp
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_sardine_proto_init() }
func file_proto_sardine_proto_init() {
	if File_proto_sardine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_sardine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegSectionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegSectionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegSectionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnRegSectionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReBalanceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReBalanceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenUserSeqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenUserSeqResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserSeqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserSeqResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenUserMultiSeqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenUserMultiSeqResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserMultiSeqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserMultiSeqResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGenUserSeqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGenUserSeqResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetUserSeqReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sardine_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetUserSeqResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_sardine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_sardine_proto_goTypes,
		DependencyIndexes: file_proto_sardine_proto_depIdxs,
		MessageInfos:      file_proto_sardine_proto_msgTypes,
	}.Build()
	File_proto_sardine_proto = out.File
	file_proto_sardine_proto_rawDesc = nil
	file_proto_sardine_proto_goTypes = nil
	file_proto_sardine_proto_depIdxs = nil
}
